import { Produit } from '../models/produit';

export const CATALOGUE: Produit[] = [
  {
    nom: 'shoes',
    prix: '150dt',
    id: 'C1',
    image: 'assets/shoe.jpg',
    description: 'cool shoes',
  },
  {
    nom: 'shirt',
    prix: '250dt',
    id: 'C2',
    image: 'assets/shirt.jpg',
    description: 'nice shirt',
  },
  {
    nom: 'dress',
    prix: '350dt',
    id: 'C3',
    image: 'assets/dress.jpg',
    description: 'amazing dress',
  },
  {
    nom: 'shoes',
    prix: '150dt',
    id: 'C1',
    image: 'assets/shoe.jpg',
    description: 'cool shoes',
  },
  {
    nom: 'shirt',
    prix: '250dt',
    id: 'C2',
    image: 'assets/shirt.jpg',
    description: 'nice shirt',
  },
  {
    nom: 'dress',
    prix: '350dt',
    id: 'C3',
    image: 'assets/dress.jpg',
    description: 'amazing dress',
  },
  {
    nom: 'shoes',
    prix: '150dt',
    id: 'C1',
    image: 'assets/shoe.jpg',
    description: 'cool shoes',
  },
  {
    nom: 'shirt',
    prix: '250dt',
    id: 'C2',
    image: 'assets/shirt.jpg',
    description: 'nice shirt',
  },
  {
    nom: 'dress',
    prix: '350dt',
    id: 'C3',
    image: 'assets/dress.jpg',
    description: 'amazing dress',
  },
  {
    nom: 'shoes',
    prix: '150dt',
    id: 'C1',
    image: 'assets/shoe.jpg',
    description: 'cool shoes',
  },
  {
    nom: 'shirt',
    prix: '250dt',
    id: 'C2',
    image: 'assets/shirt.jpg',
    description: 'nice shirt',
  },
  {
    nom: 'dress',
    prix: '350dt',
    id: 'C3',
    image: 'assets/dress.jpg',
    description: 'amazing dress',
  },
];
